name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: se-vel-v2

      - name: Build project
        run: npm run build
        working-directory: se-vel-v2

      - name: Build storybook
        run: npm run build-storybook
        working-directory: se-vel-v2

      - name: Copy Storybook to build folder
        run: cp -r se-vel-v2/storybook-static ./se-vel-v2/build/storybook

      - name: Copy conf files
        run: cp CNAME ./se-vel-v2/build/CNAME && cp 54071fdb.html ./se-vel-v2/build/54071fdb.html && cp PrivacyPolicy.md ./se-vel-v2/build/PrivacyPolicy.md

      - name: Copy v1
        run: cp -r se-vel-v1 ./se-vel-v2/build/v1

      - name: Copy landing3d
        run: cp -r landing3d ./se-vel-v2/build/landing3d

      - name: Copy rendering
        run: cp -r rendering ./se-vel-v2/build/rendering

      - name: Copy watch-finder
        run: cp -r watch-finder ./se-vel-v2/build/watch-finder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./se-vel-v2/build
          publish_branch: gh-pages
          force_orphan: true
